package StringConcatModule;


/**
* StringConcatModule/StringConcat.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringConcatModule.idl
* Monday, 29 May, 2023 7:02:57 AM IST
*/

public interface StringConcat extends StringConcatOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface StringConcat
