package CalculatorModule;


/**
* CalculatorModule/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculatorModule.idl
* Monday, 29 May, 2023 7:11:22 AM IST
*/

public interface CalculatorOperations 
{
  float add (float num1, float num2);
  float subtract (float num1, float num2);
  float multiply (float num1, float num2);
  float divide (float num1, float num2);
} // interface CalculatorOperations
